[package]
name = "bracoxide"
version = "0.1.7"
edition = "2021"
description = "A feature-rich library for brace pattern combination, permutation generation, and error handling."
repository = "https://github.com/atahabaki/bracoxide"
license = "MIT"
keywords = ["brace_expansion","parsing","combination","permutation","string_manipulation"]
categories = ["parser-implementations"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "explode_benchmark"
harness = false

[features]
default = ["advanced_range"]
variable = []
numeric_range = []
unicode_range = []
range_padding = [
  "numeric_range",
  # "unicode_range"
]
arithmetic_range = [
  "numeric_range",
  # "unicode_range"
]
advanced_range = ["numeric_range", "range_padding", "arithmetic_range"]
