[package]
name = "bracoxide"
version = "0.1.6"
edition = "2024"
description = "A feature-rich library for brace pattern combination, permutation generation, and error handling."
repository = "https://github.com/atahabaki/bracoxide"
license = "MIT"
keywords = ["brace_expansion","parsing","combination","permutation","string_manipulation"]
categories = ["parser-implementations"]

[features]
default = ["advanced_range"]
variable = []
numeric_range = []
char_range = []
emoji_range = []
range_padding = []
arithmetic_range = []
advanced_range = ["numeric_range", "char_range", "emoji_range", "range_padding", "arithmetic_range"]
